---
image:
  - Visual Studio 2022

for:
  - branches:
      only:
        - main

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly

install:
  - >-
    appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName
    rustup-init.exe
  - rustup-init.exe -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV || true
  - cargo -vV || true

build: false

test_script:
  - cargo test --all --verbose --no-fail-fast
