
name: test

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Test windows build
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - version: stable
            target: x86_64-pc-windows-msvc
          # - version: nightly
          #   target: i686-pc-windows-msvc
          # - version: nightly
          #   target: x86_64-pc-windows-gnu
          # - version: stable
          #   target: i686-pc-windows-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update --no-self-update ${{ matrix.version }} && rustup default ${{ matrix.version }}-${{ matrix.target }}
      - name: Add toolchain target
        run: rustup target add ${{ matrix.target }}
      - name: Install clippy
        run: rustup component add clippy
      - name: pp
        run: python --version
      - name: pp3
        run: python ./tests/actions/echo/main.py 123213 123
      - name: Test
        run: cargo test
